name: Rust

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  grcov:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Zinstrument-coverage"
      LLVM_PROFILE_FILE: "coverage-pid%p.profraw" 
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov
        
      - name: Test
        run: cargo test

      - name: grcov builder
        run: grcov . --binary-path target -s . -t html --branch --ignore-not-existing -o ./coverage

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-files
          path: coverage
    
